[server]
maxUploadSize = 200
maxMessageSize = 200

[theme]
primaryColor = "#E31837"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false